"""HyperISNN v3 — combined model with residual weight generation.

Per-day ISNN parameters:

    W_raw = W_base + α ⊙ ω(Z)

    W_isnn = softplus(W_raw) + ε     for positive weights
           = W_raw                    for unconstrained weights

Where:
    W_base ∈ R^P      learnable base parameters (joint with hypernet)
    α      ∈ R^P      learnable per-parameter modulation scale (init 0.01)
    ω(Z)   ∈ R^P      hypernetwork output (zero-mean at init)
    P                 = ISNNSpec.total

The shared output bias b^{out} is also a single learnable scalar held here.
"""

import math

import numpy as np
import torch
import torch.nn as nn

from .config import Config, softplus_inverse
from .hypernet import HyperNet
from .isnn import ISNNSpec, isnn2_forward, isnn2_forward_single


class HyperISNN(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()
        self.cfg = cfg
        self.spec = ISNNSpec(H=cfg.isnn.H, L=cfg.isnn.L)

        self.hyper = HyperNet(out_dim=self.spec.total, cfg=cfg.hyper)

        # Learnable base weights and per-parameter modulation scale.
        W_base = self._build_W_base()
        self.W_base = nn.Parameter(W_base)
        self.alpha  = nn.Parameter(torch.full((self.spec.total,), cfg.residual.alpha_init))

        # Shared output bias — NOT generated by hypernet.
        self.bout = nn.Parameter(torch.tensor([cfg.residual.bout_init], dtype=torch.float32))

        # Toggle for warm-up: when False, alpha is frozen at its init value
        # and the hypernetwork output ω is multiplied by 0.
        self._alpha_frozen = False

    # ------------------------------------------------------------------
    # Initialisation of W_base
    # ------------------------------------------------------------------
    def _build_W_base(self) -> torch.Tensor:
        """Initialise W_base so the ISNN at init produces a sensible mean surface."""
        cfg = self.cfg
        H = self.spec.H
        L = self.spec.L

        # Targets after softplus (= the actual weight magnitudes we want at init)
        target_input  = cfg.residual.target_input_W
        target_hidden = cfg.resolve_target_hidden_W()
        target_output = cfg.residual.target_output_W

        # Convert targets to raw values via softplus^-1
        raw_input  = softplus_inverse(target_input)
        raw_hidden = softplus_inverse(target_hidden)
        raw_output = softplus_inverse(target_output)

        W_base = torch.zeros(self.spec.total)

        # Helper: classify each positive weight as input/hidden/output
        # Input = first layer of any branch (h=0 of W^{yy}, W^{tt}, W^{xy}, W^{xt}, W^{xx0_skip})
        # Output = last layer (h = L-1) of x-branch heads (W^{xx_{L-1}}, W^{xy_{L-1}}, W^{xt_{L-1}}, W^{out})
        # Hidden = everything in between
        for name, sh in self.spec.shapes.items():
            sz = int(np.prod(sh))
            off = self.spec.offsets[name]

            if name in self.spec.pos_names:
                # Pick a target value
                if name in {"Wyy_0", "Wtt_0", "Wxy_0", "Wxt_0", "Wxx_0"}:
                    # Input-layer weights (multiply scalar input directly)
                    raw = raw_input
                elif name == "Wout":
                    raw = raw_output
                elif name in {f"Wxx_{L-1}", f"Wxy_{L-1}", f"Wxt_{L-1}"}:
                    raw = raw_output
                else:
                    # Hidden weights, including all Wxx0_h skip connections.
                    raw = raw_hidden
                W_base[off:off + sz] = raw
            else:
                # Biases: zero
                W_base[off:off + sz] = cfg.residual.free_bias_init

        return W_base

    # ------------------------------------------------------------------
    # Forward
    # ------------------------------------------------------------------
    def generate_flat_weights(
        self,
        q: torch.Tensor,                # (B, N, n_ref_features)
        mask: torch.Tensor,             # (B, N) bool
        ctx: torch.Tensor,              # (B, n_ctx_features)
    ) -> torch.Tensor:
        """Returns the (B, P) raw weight tensor (before softplus on positive entries)."""
        omega = self.hyper(q, mask, ctx)             # (B, P)
        if self._alpha_frozen:
            omega = omega * 0.0                      # disable hypernet during warm-up
        # (P,) * (B, P) broadcasts — alpha is shared across episodes.
        return self.W_base.unsqueeze(0) + self.alpha.unsqueeze(0) * omega

    def forward(
        self,
        q: torch.Tensor, mask: torch.Tensor, ctx: torch.Tensor,
        m: torch.Tensor, T: torch.Tensor, r: torch.Tensor,
    ) -> torch.Tensor:
        """Returns C/S of shape (B, M, 1)."""
        flat = self.generate_flat_weights(q, mask, ctx)
        return isnn2_forward(
            flat, self.spec, m, T, r, self.bout,
            scale_m=self.cfg.isnn.scale_m,
            scale_t=self.cfg.isnn.scale_t,
            pos_floor=self.cfg.residual.pos_floor,
        )

    # ------------------------------------------------------------------
    # Single-episode helpers (constraint check / inference)
    # ------------------------------------------------------------------
    @torch.no_grad()
    def predict_surface(
        self,
        q: torch.Tensor, mask: torch.Tensor, ctx: torch.Tensor,
        m_grid: torch.Tensor, T_grid: torch.Tensor, r_grid: torch.Tensor,
    ) -> torch.Tensor:
        """For a SINGLE episode (B=1), evaluate C/S on an arbitrary (m, T) grid."""
        flat = self.generate_flat_weights(q, mask, ctx)        # (1, P)
        return isnn2_forward_single(
            flat[0], self.spec, m_grid, T_grid, r_grid, self.bout,
            scale_m=self.cfg.isnn.scale_m,
            scale_t=self.cfg.isnn.scale_t,
            pos_floor=self.cfg.residual.pos_floor,
        )

    # ------------------------------------------------------------------
    # Warm-up control
    # ------------------------------------------------------------------
    def freeze_alpha(self):
        """Disable the hypernet contribution and freeze alpha at its init value."""
        self._alpha_frozen = True
        self.alpha.requires_grad_(False)
        # Also freeze hypernet params (optional: still let them get gradients for free
        # but they won't affect output). We freeze them entirely for cleaner warm-up.
        for p in self.hyper.parameters():
            p.requires_grad_(False)

    def unfreeze_alpha(self):
        self._alpha_frozen = False
        self.alpha.requires_grad_(True)
        for p in self.hyper.parameters():
            p.requires_grad_(True)
